# apps/engine/Cargo.toml
[package]
name = "fetch-engine"
version = "0.1.0"
edition = "2024"
rust-version = "1.86"
license = "MIT"

[dependencies]
axum = "0.8.9"
ffm-parser = { git = "https://github.com/Fuyeor/markdown-parser.git", branch = "main", package = "ffm-parser" }
fon-parser = { git = "https://github.com/Fuyeor/fon-parser.git", branch = "main", package = "fon-parser" }
futures-util = "0.3.31"
jieba-rs = "0.10.3"
tempfile = "3.27.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.13.4", default-features = false, features = ["http2", "rustls", "stream"] }
redb = "4.2.0"
serde_json = "1.0"
sha2 = "0.10"
tantivy = "0.26.1"
tokio = { version = "1.48", features = ["macros", "net", "rt-multi-thread", "time"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
