[package]
name = "fetch-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web & Async
axum = "0.7"
axum-extra = { version = "0.9", features = ["cookie"] }
tokio = { version = "1", features = ["full"] }
time = "0.3.47"

# Fuyeor Official OAuth SDK
fplatform-oauth = { git = "https://github.com/Fuyeor/fplatform-oauth.git", branch = "main", features = [
  "jwt",
] }

# Serialization & Utils
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"
uuid = { version = "1.10", features = ["v7", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
hex = "0.4.3"

# HTTP Client
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "rustls-tls",
] }

# Pure Rust DNS TXT Resolver
hickory-resolver = "0.24"

# Database & ORM
sea-orm = { version = "1.1", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }

# Security & Session JWT
jsonwebtoken = { version = "10.3.0", default-features = false, features = [
  "rust_crypto",
] }

# domain-related
psl = "2.1"
idna = "1.0"
