//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::domain::Entity as Domain;
pub use super::ingestion::Entity as Ingestion;
pub use super::search_history::Entity as SearchHistory;
pub use super::sitemap::Entity as Sitemap;
pub use super::user::Entity as User;
pub use super::user_refresh_token::Entity as UserRefreshToken;
