//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "custom(\"citext\")", unique)]
    pub username: String,
    pub nickname: String,
    pub avatar: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::domain::Entity")]
    Domain,
    #[sea_orm(has_many = "super::search_history::Entity")]
    SearchHistory,
    #[sea_orm(has_many = "super::user_refresh_token::Entity")]
    UserRefreshToken,
}

impl Related<super::domain::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Domain.def()
    }
}

impl Related<super::search_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SearchHistory.def()
    }
}

impl Related<super::user_refresh_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRefreshToken.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
